"""Initial schema

Revision ID: 26cbbca6949f
Revises: 
Create Date: 2026-10-05 18:27:25.351796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base


# revision identifiers, used by Alembic.
revision: str = '26cbbca6949f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('normalized_business_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('normalized_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('normalized_email', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('website_domain', sa.String(length=255), nullable=True),
    sa.Column('has_website', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_business_id', sa.String(length=255), nullable=True),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_business_name'), ['business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_city'), ['city'], unique=False)
        batch_op.create_index('ix_businesses_city_cat', ['city', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_has_website'), ['has_website'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_normalized_business_name'), ['normalized_business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_normalized_email'), ['normalized_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_normalized_phone'), ['normalized_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_pincode'), ['pincode'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_source_business_id'), ['source_business_id'], unique=False)
        batch_op.create_index('ix_businesses_source_id', ['source', 'source_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_website_domain'), ['website_domain'], unique=False)

    op.create_table('lead_sources',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_usage',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('job_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_usage_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_usage_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_usage_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_usage_provider'), ['provider'], unique=False)

    op.create_table('users',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_key', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_hashed_key'), ['hashed_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('business_contacts',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_contacts_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_contacts_phone'), ['phone'], unique=False)

    op.create_table('business_locations',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_locations_business_id'), ['business_id'], unique=False)

    op.create_table('business_websites',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('is_https', sa.Boolean(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('technology_stack', sa.JSON(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_websites_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_websites_domain'), ['domain'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('max_leads', sa.Integer(), nullable=False),
    sa.Column('enrich_contacts', sa.Boolean(), nullable=False),
    sa.Column('analyze_websites', sa.Boolean(), nullable=False),
    sa.Column('ai_qualification', sa.Boolean(), nullable=False),
    sa.Column('google_sheet_sync', sa.Boolean(), nullable=False),
    sa.Column('max_apify_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_apollo_credits', sa.Integer(), nullable=False),
    sa.Column('max_ai_requests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('leads_discovered', sa.Integer(), nullable=False),
    sa.Column('leads_enriched', sa.Integer(), nullable=False),
    sa.Column('leads_scored', sa.Integer(), nullable=False),
    sa.Column('leads_exported', sa.Integer(), nullable=False),
    sa.Column('created_by_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('lead_scores',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('deterministic_score', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('scoring_breakdown', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.create_index('ix_lead_score_final', ['final_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_scores_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_scores_final_score'), ['final_score'], unique=False)

    op.create_table('outreach_status',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_status_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_status_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_outreach_status_status'), ['status'], unique=False)

    op.create_table('website_analysis',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=False),
    sa.Column('is_https', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('security_headers', sa.JSON(), nullable=True),
    sa.Column('performance_indicators', sa.JSON(), nullable=True),
    sa.Column('emails_found', sa.JSON(), nullable=False),
    sa.Column('phones_found', sa.JSON(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('website_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_analysis_business_id'), ['business_id'], unique=False)

    op.create_table('ai_decisions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('campaign_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('lead_quality', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('recommended_service', sa.String(length=100), nullable=False),
    sa.Column('opportunity', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('needs_enrichment', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_decisions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_decisions_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_leads',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('campaign_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('business_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.create_index('ix_campaign_lead_uniq', ['campaign_id', 'business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_campaign_leads_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_leads_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_leads_status'), ['status'], unique=False)

    op.create_table('discovery_jobs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('campaign_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_jobs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_jobs_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovery_jobs_status'), ['status'], unique=False)

    op.create_table('enrichment_jobs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('lead_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('campaign_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrichment_jobs_status'), ['status'], unique=False)

    op.create_table('google_sheet_exports',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('campaign_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('spreadsheet_id', sa.String(length=255), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('total_rows_exported', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_sheet_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_sheet_exports_campaign_id'), ['campaign_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_sheet_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_sheet_exports_campaign_id'))

    op.drop_table('google_sheet_exports')
    with op.batch_alter_table('enrichment_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_lead_id'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_celery_task_id'))
        batch_op.drop_index(batch_op.f('ix_enrichment_jobs_campaign_id'))

    op.drop_table('enrichment_jobs')
    with op.batch_alter_table('discovery_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_discovery_jobs_celery_task_id'))
        batch_op.drop_index(batch_op.f('ix_discovery_jobs_campaign_id'))

    op.drop_table('discovery_jobs')
    with op.batch_alter_table('campaign_leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_leads_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_leads_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_leads_business_id'))
        batch_op.drop_index('ix_campaign_lead_uniq')

    op.drop_table('campaign_leads')
    with op.batch_alter_table('ai_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_decisions_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_ai_decisions_business_id'))

    op.drop_table('ai_decisions')
    with op.batch_alter_table('website_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_analysis_business_id'))

    op.drop_table('website_analysis')
    with op.batch_alter_table('outreach_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_status_status'))
        batch_op.drop_index(batch_op.f('ix_outreach_status_business_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_status_assigned_to_id'))

    op.drop_table('outreach_status')
    with op.batch_alter_table('lead_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_scores_final_score'))
        batch_op.drop_index(batch_op.f('ix_lead_scores_business_id'))
        batch_op.drop_index('ix_lead_score_final')

    op.drop_table('lead_scores')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_created_by_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('business_websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_websites_domain'))
        batch_op.drop_index(batch_op.f('ix_business_websites_business_id'))

    op.drop_table('business_websites')
    with op.batch_alter_table('business_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_locations_business_id'))

    op.drop_table('business_locations')
    with op.batch_alter_table('business_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_contacts_phone'))
        batch_op.drop_index(batch_op.f('ix_business_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_business_contacts_business_id'))

    op.drop_table('business_contacts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_hashed_key'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('provider_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_usage_operation'))
        batch_op.drop_index(batch_op.f('ix_provider_usage_job_id'))
        batch_op.drop_index(batch_op.f('ix_provider_usage_created_at'))
        batch_op.drop_index(batch_op.f('ix_provider_usage_campaign_id'))

    op.drop_table('provider_usage')
    op.drop_table('lead_sources')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_website_domain'))
        batch_op.drop_index(batch_op.f('ix_businesses_state'))
        batch_op.drop_index('ix_businesses_source_id')
        batch_op.drop_index(batch_op.f('ix_businesses_source_business_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_source'))
        batch_op.drop_index(batch_op.f('ix_businesses_pincode'))
        batch_op.drop_index(batch_op.f('ix_businesses_normalized_phone'))
        batch_op.drop_index(batch_op.f('ix_businesses_normalized_email'))
        batch_op.drop_index(batch_op.f('ix_businesses_normalized_business_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_has_website'))
        batch_op.drop_index(batch_op.f('ix_businesses_district'))
        batch_op.drop_index('ix_businesses_city_cat')
        batch_op.drop_index(batch_op.f('ix_businesses_city'))
        batch_op.drop_index(batch_op.f('ix_businesses_category'))
        batch_op.drop_index(batch_op.f('ix_businesses_business_name'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
